//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceInteraction.KenobiReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KenobiReference.KenobiServiceSoap")]
    public interface KenobiServiceSoap {
        
        // CODEGEN: Generating message contract since element name log from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHi", ReplyAction="*")]
        ServiceInteraction.KenobiReference.SayHiResponse SayHi(ServiceInteraction.KenobiReference.SayHiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHi", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceInteraction.KenobiReference.SayHiResponse> SayHiAsync(ServiceInteraction.KenobiReference.SayHiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHi", Namespace="http://tempuri.org/", Order=0)]
        public ServiceInteraction.KenobiReference.SayHiRequestBody Body;
        
        public SayHiRequest() {
        }
        
        public SayHiRequest(ServiceInteraction.KenobiReference.SayHiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint greetingsCounter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string log;
        
        public SayHiRequestBody() {
        }
        
        public SayHiRequestBody(uint greetingsCounter, string log) {
            this.greetingsCounter = greetingsCounter;
            this.log = log;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHiResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceInteraction.KenobiReference.SayHiResponseBody Body;
        
        public SayHiResponse() {
        }
        
        public SayHiResponse(ServiceInteraction.KenobiReference.SayHiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayHiResult;
        
        public SayHiResponseBody() {
        }
        
        public SayHiResponseBody(string SayHiResult) {
            this.SayHiResult = SayHiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KenobiServiceSoapChannel : ServiceInteraction.KenobiReference.KenobiServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KenobiServiceSoapClient : System.ServiceModel.ClientBase<ServiceInteraction.KenobiReference.KenobiServiceSoap>, ServiceInteraction.KenobiReference.KenobiServiceSoap {
        
        public KenobiServiceSoapClient() {
        }
        
        public KenobiServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KenobiServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KenobiServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KenobiServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceInteraction.KenobiReference.SayHiResponse ServiceInteraction.KenobiReference.KenobiServiceSoap.SayHi(ServiceInteraction.KenobiReference.SayHiRequest request) {
            return base.Channel.SayHi(request);
        }
        
        public string SayHi(uint greetingsCounter, string log) {
            ServiceInteraction.KenobiReference.SayHiRequest inValue = new ServiceInteraction.KenobiReference.SayHiRequest();
            inValue.Body = new ServiceInteraction.KenobiReference.SayHiRequestBody();
            inValue.Body.greetingsCounter = greetingsCounter;
            inValue.Body.log = log;
            ServiceInteraction.KenobiReference.SayHiResponse retVal = ((ServiceInteraction.KenobiReference.KenobiServiceSoap)(this)).SayHi(inValue);
            return retVal.Body.SayHiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceInteraction.KenobiReference.SayHiResponse> ServiceInteraction.KenobiReference.KenobiServiceSoap.SayHiAsync(ServiceInteraction.KenobiReference.SayHiRequest request) {
            return base.Channel.SayHiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceInteraction.KenobiReference.SayHiResponse> SayHiAsync(uint greetingsCounter, string log) {
            ServiceInteraction.KenobiReference.SayHiRequest inValue = new ServiceInteraction.KenobiReference.SayHiRequest();
            inValue.Body = new ServiceInteraction.KenobiReference.SayHiRequestBody();
            inValue.Body.greetingsCounter = greetingsCounter;
            inValue.Body.log = log;
            return ((ServiceInteraction.KenobiReference.KenobiServiceSoap)(this)).SayHiAsync(inValue);
        }
    }
}
