//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceInteraction.GrievousReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GrievousReference.GrievousServiceSoap")]
    public interface GrievousServiceSoap {
        
        // CODEGEN: Generating message contract since element name log from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHi", ReplyAction="*")]
        ServiceInteraction.GrievousReference.SayHiResponse SayHi(ServiceInteraction.GrievousReference.SayHiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayHi", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceInteraction.GrievousReference.SayHiResponse> SayHiAsync(ServiceInteraction.GrievousReference.SayHiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHi", Namespace="http://tempuri.org/", Order=0)]
        public ServiceInteraction.GrievousReference.SayHiRequestBody Body;
        
        public SayHiRequest() {
        }
        
        public SayHiRequest(ServiceInteraction.GrievousReference.SayHiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public uint greetingsCounter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string log;
        
        public SayHiRequestBody() {
        }
        
        public SayHiRequestBody(uint greetingsCounter, string log) {
            this.greetingsCounter = greetingsCounter;
            this.log = log;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SayHiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SayHiResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceInteraction.GrievousReference.SayHiResponseBody Body;
        
        public SayHiResponse() {
        }
        
        public SayHiResponse(ServiceInteraction.GrievousReference.SayHiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SayHiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SayHiResult;
        
        public SayHiResponseBody() {
        }
        
        public SayHiResponseBody(string SayHiResult) {
            this.SayHiResult = SayHiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GrievousServiceSoapChannel : ServiceInteraction.GrievousReference.GrievousServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrievousServiceSoapClient : System.ServiceModel.ClientBase<ServiceInteraction.GrievousReference.GrievousServiceSoap>, ServiceInteraction.GrievousReference.GrievousServiceSoap {
        
        public GrievousServiceSoapClient() {
        }
        
        public GrievousServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrievousServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrievousServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrievousServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceInteraction.GrievousReference.SayHiResponse ServiceInteraction.GrievousReference.GrievousServiceSoap.SayHi(ServiceInteraction.GrievousReference.SayHiRequest request) {
            return base.Channel.SayHi(request);
        }
        
        public string SayHi(uint greetingsCounter, string log) {
            ServiceInteraction.GrievousReference.SayHiRequest inValue = new ServiceInteraction.GrievousReference.SayHiRequest();
            inValue.Body = new ServiceInteraction.GrievousReference.SayHiRequestBody();
            inValue.Body.greetingsCounter = greetingsCounter;
            inValue.Body.log = log;
            ServiceInteraction.GrievousReference.SayHiResponse retVal = ((ServiceInteraction.GrievousReference.GrievousServiceSoap)(this)).SayHi(inValue);
            return retVal.Body.SayHiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceInteraction.GrievousReference.SayHiResponse> ServiceInteraction.GrievousReference.GrievousServiceSoap.SayHiAsync(ServiceInteraction.GrievousReference.SayHiRequest request) {
            return base.Channel.SayHiAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceInteraction.GrievousReference.SayHiResponse> SayHiAsync(uint greetingsCounter, string log) {
            ServiceInteraction.GrievousReference.SayHiRequest inValue = new ServiceInteraction.GrievousReference.SayHiRequest();
            inValue.Body = new ServiceInteraction.GrievousReference.SayHiRequestBody();
            inValue.Body.greetingsCounter = greetingsCounter;
            inValue.Body.log = log;
            return ((ServiceInteraction.GrievousReference.GrievousServiceSoap)(this)).SayHiAsync(inValue);
        }
    }
}
